function [result_foi, result_err] = estimate_foi_with_maternality(...
                                                ages, ...
                                                seroprev_data, ...
                                                initial_guess)
    [result_foi, result_err] = fminsearchbnd(...
        @(foi) get_l2_error_from_foi_with_maternality(ages, ...
                                                seroprev_data, ...
                                                foi), ...
        initial_guess, 0);
end

